before_script:
  - "mysql -e 'create database sequelize_test;'"
  - "psql -c 'create database sequelize_test;' -U postgres"

script:
  - "make test"

notifications:
  email:
    - me@danieldurante.com

env:
  - DB=mysql DIALECT=mysql
  - DB=mysql DIALECT=postgres SEQ_USER=postgres
  - DB=mysql DIALECT=mariadb

language: node_js

node_js:
  - "0.10"

branches:
  only:
    - master

cache:
  directories:
    - node_modules